In [7]:
import pandas as pd
import random

In [8]:
recipes = pd.read_csv('Nutriv.csv')

In [13]:
recipes

,title,calories,protein,fat,sodium,almond,appetizer,apricot,bread,breakfast,...,soy free,sugar conscious,tree nut free,vegan,vegetarian,walnut,wheat/gluten-free,whole wheat,zucchini,snack
0,"""Blanketed"" Eggplant",1386,9,133,105,0,1,0,0,0,...,0,0,0,1,1,0,0,0,0,0
1,"""Bloody Mary"" Tomato Toast with Celery and Hor...",189,2,16,517,0,1,0,0,0,...,1,0,1,0,1,0,0,0,0,0
2,"""California Roll"" Salad",369,9,13,953,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,"""Cocotte"" of Vegetables",196,8,14,272,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,"""Drunken"" Pork Chops",153,12,8,40,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8495,Zucchini-Cilantro Dip,162,4,14,279,0,1,0,0,0,...,1,0,1,0,1,0,0,0,1,0
8496,Zucchini-Herb Fritters with Garlic Yogurt,153,3,13,354,0,0,0,0,0,...,1,1,1,0,1,0,0,0,1,0
8497,"Zucchini, Cheese and Herb Fritters",295,2,30,194,0,1,0,0,0,...,1,1,1,0,1,0,1,0,1,0
8498,"Zucchini, Corn, and Basil Fusilli with Bacon",511,17,18,305,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
8499,"Zucchini, Tomato, and Corn Salad",209,4,15,745,0,0,0,0,0,...,1,0,1,1,1,0,1,0,1,0

In [14]:
def filter_by_calories(df, min_calories, max_calories):
    return df[(df['calories'] >= min_calories) & (df['calories'] <= max_calories) & (df['breakfast'] >= 1)]

In [15]:
filtered_recipes = filter_by_calories(recipes, 400, 600)

In [16]:
filtered_recipes

,title,calories,protein,fat,sodium,almond,appetizer,apricot,bread,breakfast,...,soy free,sugar conscious,tree nut free,vegan,vegetarian,walnut,wheat/gluten-free,whole wheat,zucchini,snack
18,3-Ingredient Shakshuka,454,13,31,2111,0,0,0,0,1,...,1,0,1,0,1,0,1,0,0,0
58,Almond-Barley Porridge with Fruit,416,9,18,193,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
223,Asparagus and Goat Cheese Frittata,482,24,41,1533,0,0,0,0,1,...,1,1,1,0,1,0,1,0,0,0
353,Banana Pancakes with Pineapple and CrÃ¨me FraÃ®che,523,8,26,300,0,0,0,0,1,...,1,0,1,0,1,0,0,0,0,0
356,Banana-Cinnamon French Toast,505,17,26,356,0,0,0,0,1,...,1,0,1,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7798,Toasted Walnut Buttermilk Pancakes with Cranbe...,518,10,14,641,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0
7801,Tofu Scramble with Yukon Gold and Sweet Potato...,425,38,24,185,0,0,0,0,1,...,0,0,1,1,1,0,1,0,0,0
8000,Turkey Hash,461,21,27,122,0,0,0,0,1,...,1,0,1,0,0,0,1,0,0,0
8229,Walnut Griddle Cakes with Orange Butter,549,13,36,544,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0
8364,Whole-Wheat Pancakes with Blackberry Syrup,587,11,18,949,0,0,0,0,1,...,1,0,1,0,1,0,0,1,0,0

In [10]:
filtered_recipes.loc[:, 'title':'breakfast']

NameError: name 'filtered_recipes' is not defined

In [10]:
def filter_by_cal(df, min_calories, max_calories):
    return df[(df['calories'] >= min_calories) & (df['calories'] <= max_calories) & (df['breakfast'] >= 1)]

filter_C =filter_by_cal(recipes, 400, 600)
recommended_recipe = filter_C.sample(n=2)

# Step 5: Print out the recommended recipes
print(recommended_recipe.loc[:, 'title':'breakfast'])

                                title  rating  calories  protein   fat  \
852   Jam Filled Buttermilk Biscuits    4.375     484.0      8.0  21.0
7027           Almond-Raisin Granola    4.375     555.0     14.0  23.0

      sodium  #cakeweek  #wasteless  22-minute meals  3-ingredient recipes  \
852    622.0        0.0         0.0              0.0                   0.0
7027   176.0        0.0         0.0              0.0                   0.0

      ...  bon appÃ©tit  bon appï¿½ï¿½tit  boston  bourbon  braise  bran  brandy  \
852   ...          1.0           0.0     0.0      0.0     0.0   0.0     0.0
7027  ...          1.0           0.0     0.0      0.0     0.0   0.0     0.0

      bread  breadcrumbs  breakfast
852     0.0          0.0        1.0
7027    0.0          0.0        1.0

[2 rows x 73 columns]

In [6]:
recipes.columns

Index(['title', 'calories', 'protein', 'fat', 'sodium', '#cakeweek',
       '#wasteless', '22-minute meals', '3-ingredient recipes',
       '30 days of groceries',
       ...
       'yellow squash', 'yogurt', 'yonkers', 'yuca', 'zucchini', 'cookbooks',
       'leftovers', 'snack', 'snack week', 'turkey'],
      dtype='object', length=676)

In [7]:
recipes.describe()

,calories,protein,fat,sodium,#cakeweek,#wasteless,22-minute meals,3-ingredient recipes,30 days of groceries,advance prep required,...,yellow squash,yogurt,yonkers,yuca,zucchini,cookbooks,leftovers,snack,snack week,turkey
count,1.525000e+04,15218.000000,1.521200e+04,1.524800e+04,19126.000000,19126.000000,19126.000000,19126.000000,19126.000000,19126.000000,...,19126.000000,19126.000000,19126.000000,19126.000000,19126.000000,19126.000000,19126.000000,19126.000000,19126.000000,19126.000000
mean,6.594592e+03,104.441057,3.615227e+02,6.495098e+03,0.000314,0.000052,0.000889,0.001412,0.000366,0.005594,...,0.001307,0.027554,0.000052,0.000314,0.015581,0.000157,0.000366,0.001412,0.000993,0.023685
std,3.670195e+05,3924.142044,2.089309e+04,3.407207e+05,0.017710,0.007231,0.029801,0.037547,0.019128,0.074589,...,0.036131,0.163696,0.007231,0.017710,0.123850,0.012524,0.019128,0.037547,0.031504,0.152070
min,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.040000e+02,3.000000,9.000000e+00,9.800000e+01,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,3.430000e+02,9.000000,1.800000e+01,3.140000e+02,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,5.970000e+02,28.000000,3.400000e+01,7.352500e+02,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,3.011122e+07,236489.000000,1.722763e+06,2.767511e+07,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [19]:
#consider the range 1500 to 3000
minc=  1500
maxc= 3000

filtered_recipes = filter_by_calories(recipes, 900, 1200)

In [20]:
filtered_recipes

,title,calories,protein,fat,sodium,almond,appetizer,apricot,bread,breakfast,...,soy free,sugar conscious,tree nut free,vegan,vegetarian,walnut,wheat/gluten-free,whole wheat,zucchini,snack
323,"Bagel Chips with Smoked Salmon, Capers, and Le...",934,40,12,1667,0,1,0,0,1,...,1,0,1,0,0,0,0,0,0,0
4777,Oat and Dried Fruit Cereal with Honey and Yogurt,1091,21,23,94,0,0,0,0,1,...,1,0,0,0,1,0,1,0,0,0
5849,Red-Flannel Salmon Hash with Poached Eggs and ...,1015,24,83,13767,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [54]:
def filter_by_cal2(df, min_calories, max_calories):
    return df[(df['calories'] >= min_calories) & (df['calories'] <= max_calories) &( (df['lunch']>=1) | df['dinner']>=1 | (df['breakfast']>=1))]

filter_C =filter_by_cal2(recipes, 900, 1200)
filter_C = filter_C.loc[:,'title':'lunch']

In [58]:
recommended_recipe = filter_C.sample(n=2)

recommended_recipe

,title,calories,protein,fat,sodium,almond,appetizer,apricot,bread,breakfast,...,dessert,dinner,drink,drinks,egg,fig,hazelnut,healthy,high fiber,lunch
27,A Simple Roast Turkey,1033,139,47,1251,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
7289,Spicy Vietnamese Beef and Noodle Soup,1024,59,61,1160,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1